services:
  - type: web
    name: inhospital-forecast-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: MODEL_PATH
        value: fixed_rf_model.joblib 