services:
  - type: web
    name: inhospital-forecast-api
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    healthCheckPath: "/api/health"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MODEL_PATH
        value: "./fixed_rf_model.joblib"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false