name: Deploy Python App to Azure Static Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd api && pip install --only-binary=scikit-learn -r requirements.txt

    - name: Build static HTML content
      run: |
        cd frontend
        python build_app.py

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r frontend/build/* deployment/
        cp -r api/* deployment/

    # Azure Static Web Appsにデプロイ
    - name: Deploy to Azure Static Web App
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "deployment" # アプリのソースコードの場所
        api_location: "deployment/api" # APIのソースコードの場所
        output_location: "" # ビルド出力の場所（必要に応じて調整）
        skip_app_build: true # 既にビルド済みのため 