name: Azure Static Web Apps CI/CD

# Deployment configuration for inhospitalforcast2
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r frontend/requirements.txt
          pip install -r api/requirements.txt

      - name: Create static content
        run: |
          mkdir -p frontend/build
          cat > frontend/build/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <title>InHospital Forecast</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
          </head>
          <body>
              <div class="container py-4">
                  <h1>InHospital Forecast API</h1>
                  <p>Available API endpoints:</p>
                  <ul>
                      <li><a href="/api/DataFunction">/api/DataFunction</a></li>
                      <li><a href="/api/PredictFunction">/api/PredictFunction</a></li>
                  </ul>
              </div>
          </body>
          </html>
          EOL

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/build"
          api_location: "api"
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
          app_location: "frontend/build" 