name: Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: inhospital-forecast    # Azure Web Appの名前
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flask gunicorn

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r static_app/* deployment/
        cp -r fixed_rf_model.joblib deployment/
        cp -r requirements.txt deployment/
        echo "web: gunicorn --chdir static_app api:app --bind=0.0.0.0:8000" > deployment/Procfile

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment 