name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      # Pythonセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'
      
      # 依存関係のインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-build-isolation -r frontend/requirements.txt
          pip install --no-build-isolation -r api/requirements.txt
      
      # フロントエンドの静的ファイル作成（シンプル化）
      - name: Create simple frontend
        run: |
          mkdir -p frontend/build
          echo '<!DOCTYPE html><html><head><title>InHospital Forecast</title></head><body><h1>InHospital Forecast API</h1><p>API endpoints available at:</p><ul><li><a href="/api/DataFunction">/api/DataFunction</a></li><li><a href="/api/PredictFunction">/api/PredictFunction</a></li></ul></body></html>' > frontend/build/index.html
          ls -la frontend/build
      
      # デバッグ情報
      - name: Debug environment
        run: |
          echo "Current directory structure:"
          find . -type d -not -path "*/\.*" | sort
          echo "Secret availability check:"
          if [ -n "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then echo "Token is set"; else echo "Token is NOT set"; fi
      
      # Static Web Appsへのデプロイ
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "api"
          output_location: "build"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
          app_location: "frontend"  