name: Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: inhospital-forecast    # Azure Web Appの名前を設定
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd api && pip install --only-binary=scikit-learn -r requirements.txt

    - name: Build static HTML content
      run: |
        cd frontend
        python build_app.py

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r frontend/build/* deployment/
        cp -r api/* deployment/
        echo "web: gunicorn --bind=0.0.0.0:8000 api.app:app" > deployment/Procfile

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment 