name: Deploy Python App to Azure Web App

on:
  push:
    branches:
      - main
      - restore-original-ui
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: inhospital-forecast    # Azure Web Appの名前
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r *.py deployment/
        cp -r *.csv deployment/ || true
        cp -r *.joblib deployment/ || true
        cp -r requirements.txt deployment/
        echo "web: streamlit run app.py --server.port=\$PORT --server.address=0.0.0.0" > deployment/Procfile

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment 