name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - deploy-specific-commit
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd api && pip install --only-binary=scikit-learn -r requirements.txt

      - name: Build static HTML content
        run: |
          cd frontend
          python build_app.py

      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r frontend/build/* deployment/
          cp -r api/* deployment/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "deployment"
          api_location: "deployment/api"
          output_location: ""
          skip_app_build: true 